# This file is auto-generated by the Collision Presets editor plugin.
# Do not edit manually.
class_name CollisionPresets
const Player := "Player"
const Small_Enemy := "Small Enemy"
const Large_Enemy := "Large Enemy"

static func all() -> PackedStringArray:
	return PackedStringArray([
		Player,
		Small_Enemy,
		Large_Enemy
	])
